title = getTitle();
run("Split Channels");
selectWindow("C1-" + title);
title_c1 = getTitle();
run("Z Project...", "projection=[Average Intensity]");
title_zproj_BF = getTitle();
selectWindow(title_c1);
resetMinAndMax();
close();
selectWindow("C2-" + title);
title_c2 = getTitle();
run("Z Project...", "projection=[Max Intensity]");
selectWindow(title_c2);
resetMinAndMax();
close();
resetMinAndMax();
selectWindow(title_zproj_BF);
run("Threshold...");