title = getTitle();
run("Make Substack...", "frames=1-10,12-22");
title_color = getTitle();
run("Z Project...", "projection=[Max Intensity]");
title_zproj_FL = getTitle();
title_zproj_FL = substring(title_zproj_FL,4);
rename(title_zproj_FL);
resetMinAndMax();
selectWindow(title_color);
close();
selectWindow(title);
run("Make Substack...", "frames=11");
title_BF = getTitle();
selectWindow(title_BF);
resetMinAndMax();
selectWindow(title);
close();
selectWindow(title_BF);
run("Threshold...");